/*---------------------------------------------------------------------------------------------
 *  各端最小可导入/可打开脚手架（相对 exports/<target>/ 的路径 → 文件内容）
 *  占位符：__PACKAGE_NAME__、__PREVIEW_URL__、__SNAPSHOT_TAKEN_AT__
 *--------------------------------------------------------------------------------------------*/

import { CrossPlatformTargetId } from './crossPlatformExportTypes.js';

export const TEMPLATE_PLACEHOLDERS = {
	packageName: '__PACKAGE_NAME__',
	previewUrl: '__PREVIEW_URL__',
	snapshotAt: '__SNAPSHOT_TAKEN_AT__',
} as const;

function fillPlaceholders(content: string, packageName: string, previewUrl: string, snapshotAt: string): string {
	return content
		.replaceAll(TEMPLATE_PLACEHOLDERS.packageName, packageName)
		.replaceAll(TEMPLATE_PLACEHOLDERS.previewUrl, previewUrl)
		.replaceAll(TEMPLATE_PLACEHOLDERS.snapshotAt, snapshotAt);
}

/** 返回相对 exports/<target>/ 的路径 → 模板正文（已替换占位符） */
export function getScaffoldFiles(
	target: CrossPlatformTargetId,
	packageName: string,
	previewUrl: string,
	snapshotAt: string,
): Map<string, string> {
	const raw = RAW_TEMPLATES[target];
	const map = new Map<string, string>();
	for (const [rel, text] of Object.entries(raw)) {
		map.set(rel, fillPlaceholders(text, packageName || 'app', previewUrl || 'http://localhost:5173', snapshotAt));
	}
	return map;
}

const WEB: Record<string, string> = {
	'project/README.md': `# Web 交付说明

- **源码真源**：当前工作区根目录即为 Web 应用源码；预览 URL 为 \`${TEMPLATE_PLACEHOLDERS.previewUrl}\`。
- **构建**：在仓库根目录执行 \`npm run build\` 或 \`pnpm build\`（以 package.json 为准）。
- **IR 快照时间**：${TEMPLATE_PLACEHOLDERS.snapshotAt}

本目录仅作跨端导出占位；无需复制整仓到此。
`,
};

const IOS: Record<string, string> = {
	'project/README.md': `# iOS 工程指引

- 包名/产品名参考：\`${TEMPLATE_PLACEHOLDERS.packageName}\`
- 建议在 macOS 上使用 **Xcode** 新建 SwiftUI 或 React Native 工程后，将业务模块按 \`exports/ios/GENERATION.md\` 与 LLM 生成文件对齐。
- IR 快照：${TEMPLATE_PLACEHOLDERS.snapshotAt}

已包含最小 \`AppEntry.swift\` 占位，可在 Xcode 中创建 App target 并加入该文件试编译。
`,
	'project/Sources/AppEntry.swift': `import SwiftUI

@main
struct PlaceholderApp: App {
    var body: some Scene {
        WindowGroup {
            Text("Cross-platform export placeholder — replace with real UI")
        }
    }
}
`,
};

const ANDROID: Record<string, string> = {
	'project/README.md': `# Android 工程指引

- 应用名参考：\`${TEMPLATE_PLACEHOLDERS.packageName}\`
- 使用 **Android Studio** 新建 Empty Compose 或 React Native 工程，将模块按 \`exports/android/GENERATION.md\` 落地。
- IR 快照：${TEMPLATE_PLACEHOLDERS.snapshotAt}

可在 \`project/stub\` 下放置由生成管线追加的 Kotlin 文件。
`,
	'project/stub/.gitkeep': '',
};

const WECHAT: Record<string, string> = {
	'project/miniprogram/app.json': `{
  "pages": ["pages/index/index"],
  "window": {
    "navigationBarTitleText": "__PACKAGE_NAME__"
  },
  "sitemapLocation": "sitemap.json"
}
`,
	'project/miniprogram/app.ts': `App({
  onLaunch() {},
});
`,
	'project/miniprogram/sitemap.json': `{
  "rules": [{ "action": "allow", "page": "*" }]
}
`,
	'project/miniprogram/pages/index/index.json': `{
  "usingComponents": {}
}
`,
	'project/miniprogram/pages/index/index.ts': `Page({
  data: { title: 'Hello from export' },
  onLoad() {},
});
`,
	'project/miniprogram/pages/index/index.wxml': `<view class="page">
  <text>Cross-platform export — replace with real UI</text>
</view>
`,
	'project/miniprogram/pages/index/index.wxss': `.page { padding: 24rpx; }
`,
	'project/project.config.json': `{
  "description": "Generated by AI Core cross-platform export",
  "packOptions": { "ignore": [] },
  "setting": { "es6": true, "minified": true },
  "compileType": "miniprogram",
  "miniprogramRoot": "miniprogram/",
  "appid": "touristappid",
  "projectname": "__PACKAGE_NAME__"
}
`,
	'project/README.md': `# 微信小程序

1. 用 **微信开发者工具** → 导入本目录 \`project/\`。
2. 将 \`appid\` 改为你的小程序 appid。
3. 预览与真机调试以微信工具为准。

IR 快照：__SNAPSHOT_TAKEN_AT__
`,
};

/** 未替换占位符的原始模板（wechat 的 app.json 等在运行时由 getScaffoldFiles 统一替换） */
const RAW_TEMPLATES: Record<CrossPlatformTargetId, Record<string, string>> = {
	web: WEB,
	ios: IOS,
	android: ANDROID,
	wechat_miniprogram: WECHAT,
};
